"""Cached post-analysis loaders for the Results tab.

Prefer JSON artifacts generated during the LUNA run; fall back to the
legacy subprocess helpers only when those artifacts are missing.
"""
from __future__ import annotations

import json
import signal
import subprocess
import tempfile
from pathlib import Path

from . import analysis_helper
from .env_manager import python_prefix, python_process_env
from .pymol_launcher import iter_pymol_candidates

IFP_SUFFIX_TO_TYPE = {"E": "EIFP", "H": "HIFP", "F": "FIFP"}

_NOISY_HELPER_MARKERS = (
    "openbabel/__init__.py",
    '"import openbabel" is deprecated',
    "warnings.warn",
    "Module 'simplejson' not available",
)


def _clean_helper_text(text: str | None) -> str:
    """Remove noisy third-party warnings from helper output."""
    cleaned: list[str] = []
    for line in str(text or "").splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        if any(marker in stripped for marker in _NOISY_HELPER_MARKERS):
            continue
        cleaned.append(line)
    return "\n".join(cleaned).strip()


def _helper_json_from_stdout(stdout: str | None) -> dict:
    for line in reversed(str(stdout or "").splitlines()):
        stripped = line.strip()
        if stripped.startswith("{") and stripped.endswith("}"):
            return json.loads(stripped)
    raise ValueError("helper stdout did not contain a JSON object")


def _helper_failure(result: subprocess.CompletedProcess, prefix: str = "Helper falhou") -> dict:
    try:
        parsed = _helper_json_from_stdout(result.stdout)
        if isinstance(parsed, dict) and parsed.get("error"):
            return parsed
    except Exception:
        pass
    detail_parts = [
        part
        for part in (_clean_helper_text(result.stderr), _clean_helper_text(result.stdout))
        if part
    ]
    detail = "\n".join(detail_parts).strip()
    if not detail:
        detail = "sem saida de erro relevante; apenas avisos conhecidos foram filtrados."
    code = int(result.returncode)
    if code < 0:
        signum = abs(code)
        try:
            signal_name = signal.Signals(signum).name
        except Exception:
            signal_name = f"signal {signum}"
        status = f"sinal {signum} ({signal_name})"
        if signum == 11:
            detail += (
                "\nO helper caiu dentro de uma biblioteca nativa durante a geração PSE "
                "do LUNA/PyMOL. Corrija a dependência nativa indicada pelo "
                "stderr/ambiente do luna-env."
            )
    else:
        status = f"exit {code}"
    return {"error": f"{prefix} ({status}):\n{detail[:2000]}"}


def _helper_invalid_output(result: subprocess.CompletedProcess) -> dict:
    detail_parts = [
        part
        for part in (_clean_helper_text(result.stdout), _clean_helper_text(result.stderr))
        if part
    ]
    detail = "\n".join(detail_parts).strip() or "sem saida relevante do helper."
    return {"error": f"Saida invalida do helper:\n{detail[:1000]}"}


def _fp_detail_cache_has_shell_levels(cached: dict | None) -> bool:
    feature_details = (cached or {}).get("feature_details") or {}
    if not feature_details:
        return True
    return all(
        isinstance(detail, dict) and "shell_level_counts" in detail
        for detail in feature_details.values()
    )


def _build_shell_level_only_fp_detail(wd: Path, ifp_type: str, output_path: Path) -> dict | None:
    """Build a non-crashing fp_detail fallback from fp_analysis metadata.

    Older GUI versions stored shell objects as pickles. Re-opening those objects
    can segfault inside native LUNA/OpenBabel/PyMOL dependencies, so this fallback
    only uses the already-safe JSON metadata. It preserves shell-level data for
    old projects; full interaction/residue detail is generated by current runs.
    """
    suffix = {value: key for key, value in IFP_SUFFIX_TO_TYPE.items()}.get(str(ifp_type).upper())
    if suffix is None:
        return None
    analysis_path = wd / "results" / "fingerprints" / f"fp_analysis_{suffix}.json"
    analysis = _load_cached_json(analysis_path)
    if not isinstance(analysis, dict):
        return None

    feature_details: dict[str, dict] = {}
    entry_index = analysis.get("entry_index") or {}
    if not isinstance(entry_index, dict):
        return None

    for entry_name, rows in entry_index.items():
        for row in rows or []:
            if not isinstance(row, dict) or "feature_id" not in row:
                continue
            try:
                feature_key = str(int(row.get("feature_id")))
            except Exception:
                feature_key = str(row.get("feature_id") or "").strip()
            if not feature_key:
                continue
            detail = feature_details.setdefault(
                feature_key,
                {
                    "interaction_counts": {},
                    "residue_counts": {},
                    "pair_counts": {},
                    "shell_level_counts": {},
                    "entries": {},
                },
            )
            entry_info = detail["entries"].setdefault(
                str(entry_name),
                {
                    "shell_count": 0,
                    "interaction_counts": {},
                    "residue_counts": {},
                    "pair_counts": {},
                    "shell_level_counts": {},
                },
            )
            breakdown = row.get("shell_level_breakdown") or {}
            if not isinstance(breakdown, dict):
                continue
            for raw_level, raw_count in breakdown.items():
                level = str(raw_level or "").strip()
                if not level:
                    continue
                try:
                    count = int(raw_count)
                except Exception:
                    count = 1
                detail["shell_level_counts"][level] = detail["shell_level_counts"].get(level, 0) + count
                entry_info["shell_level_counts"][level] = entry_info["shell_level_counts"].get(level, 0) + count
                entry_info["shell_count"] += count

    if not feature_details:
        return None

    payload = {
        "ifp_type": str(ifp_type).upper(),
        "feature_details": feature_details,
        "source": "fp_analysis_shell_levels_only",
        "detail_warning": (
            "Projeto antigo sem fp_detail completo. Reexecute o calculo com a versao atual "
            "para gerar contagens de interacao/residuo sem reabrir pickles de shells."
        ),
    }
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    return payload

_FP_SESSION_SCRIPT = r"""
import faulthandler, gzip, json, os, pickle, re, sys, warnings
from pathlib import Path

try:
    faulthandler.enable(file=sys.stderr, all_threads=True)
except Exception:
    pass

warnings.filterwarnings("ignore", message=r'.*"import openbabel".*')

from luna.mol.entry import Entry, MolFileEntry


def _safe_name(value):
    return re.sub(r"[^A-Za-z0-9_.-]+", "_", str(value)).strip("_") or "entry"


def _shell_level_key(shell):
    value = getattr(shell, "level", None)
    try:
        return str(int(value))
    except Exception:
        return str(value if value is not None else "unknown")


def _sorted_level_keys(values):
    keys = {str(value) for value in (values or []) if str(value).strip()}
    return sorted(
        keys,
        key=lambda value: (
            not str(value).lstrip("-").isdigit(),
            int(value) if str(value).lstrip("-").isdigit() else str(value),
        ),
    )


def _stage(message):
    print(f"[fp-session-helper] {message}", file=sys.stderr, flush=True)


def _restore_entry(meta):
    kind = str(meta.get("kind") or "")
    if kind == "MolFileEntry":
        preferred_type = meta.get("mol_obj_type") or "rdkit"
        candidate_types = [preferred_type]
        if preferred_type != "rdkit":
            candidate_types.append("rdkit")
        if preferred_type != "openbabel":
            candidate_types.append("openbabel")
        errors = []
        for mol_obj_type in candidate_types:
            try:
                entry = MolFileEntry.from_mol_file(
                    meta["pdb_id"],
                    meta["mol_id"],
                    meta["mol_file"],
                    bool(meta.get("is_multimol_file", False)),
                    mol_file_ext=meta.get("mol_file_ext"),
                    mol_obj_type=mol_obj_type,
                    autoload=False,
                    overwrite_mol_name=bool(meta.get("overwrite_mol_name", False)),
                    sep=meta.get("sep") or ":",
                )
                entry.get_biopython_structure()
                return entry
            except Exception as exc:
                errors.append(f"{mol_obj_type}: {type(exc).__name__}")
        raise RuntimeError("Nao foi possivel restaurar MolFileEntry: " + "; ".join(errors))
    return Entry.from_string(
        meta["entry_str"],
        is_hetatm=bool(meta.get("is_hetatm", True)),
        sep=meta.get("sep") or ":",
    )


def _entry_key(entry):
    try:
        return entry.to_string()
    except Exception:
        return str(entry)


def _entry_matches(entry, requested):
    key = _entry_key(entry)
    requested = str(requested or "").strip()
    values = {key, key.replace("/", "_"), key.replace(":", "_")}
    if requested in values:
        return True
    for value in list(values):
        values.add(value.split(":", 1)[0])
        values.add(value.split(":", 1)[-1])
    return requested in values or requested.replace("/", "_").replace(":", "_") in values


def _load_json(path):
    try:
        return json.loads(Path(path).read_text(encoding="utf-8"))
    except Exception:
        return {}


def _load_project(workdir):
    candidates = sorted(Path(workdir).glob("project_v*.pkl.gz"), reverse=True)
    if not candidates:
        raise RuntimeError(f"Nenhum project_v*.pkl.gz encontrado em {workdir}.")
    errors = []
    for candidate in candidates:
        try:
            with gzip.open(candidate, "rb") as fh:
                return pickle.load(fh), candidate
        except Exception as exc:
            errors.append(f"{candidate.name}: {type(exc).__name__}: {exc}")
    raise RuntimeError("Falha ao reabrir projeto LUNA: " + "; ".join(errors[:3]))


def _apply_ifp_settings(proj, params, ifp_type):
    from luna.interaction.fp.type import IFPType

    if params:
        if "ifp_levels" in params:
            proj.ifp_num_levels = params.get("ifp_levels")
        if "ifp_radius" in params:
            proj.ifp_radius_step = params.get("ifp_radius")
        if "ifp_length" in params:
            proj.ifp_length = params.get("ifp_length")
        if "ifp_bit" in params:
            proj.ifp_count = not params.get("ifp_bit", False)
    proj.ifp_type = getattr(IFPType, ifp_type)


def _trace_feature_shells(shell_manager, feature_id, ifp_length, ifp_count):
    unique_shells = not bool(ifp_count)
    fp = shell_manager.to_fingerprint(
        fold_to_length=int(ifp_length),
        unique_shells=unique_shells,
        count_fp=bool(ifp_count),
    )
    shells = []
    for _ori_feature, found_shells in shell_manager.trace_back_feature(
        int(feature_id),
        fp,
        unique_shells=unique_shells,
    ):
        shells.extend(found_shells)
    return shells


def _regenerate_shells_from_project(workdir, ifp_type, entry_name, feature_id):
    from luna.interaction.fp.shell import ShellGenerator

    params = _load_json(Path(workdir) / "_luna_api_params.json")
    project, project_path = _load_project(workdir)
    _apply_ifp_settings(project, params, ifp_type)
    matched_entry = None
    for candidate in list(getattr(project, "entries", []) or []):
        if _entry_matches(candidate, entry_name):
            matched_entry = candidate
            break
    if matched_entry is None:
        raise RuntimeError(f"Entry {entry_name} nao encontrada no projeto {project_path.name}.")

    entry_results = project.get_entry_results(matched_entry)
    atm_grps_mngr = entry_results.atm_grps_mngr
    shell_generator = ShellGenerator(
        project.ifp_num_levels,
        project.ifp_radius_step,
        diff_comp_classes=getattr(project, "ifp_diff_comp_classes", True),
        ifp_type=project.ifp_type,
    )
    shell_manager = shell_generator.create_shells(atm_grps_mngr)
    shells = _trace_feature_shells(
        shell_manager,
        feature_id,
        project.ifp_length,
        project.ifp_count,
    )
    if not shells:
        raise RuntimeError(f"Nenhum shell regenerado para o fingerprint {feature_id} em {entry_name}.")
    pdb_dir = (
        params.get("pdb_dir")
        or getattr(matched_entry, "pdb_file", "")
        or str(Path(workdir) / "pdbs")
    )
    return matched_entry, shells, pdb_dir, f"live_project:{project_path.name}"


def _load_cached_shell_payload(workdir, ifp_type, entry_name, feature_id):
    suffix = {"EIFP": "E", "HIFP": "H", "FIFP": "F"}.get(ifp_type)
    if suffix is None:
        raise RuntimeError(f"Tipo IFP invalido: {ifp_type}")
    payload_path = Path(workdir) / "results" / "fingerprints" / "_shells" / suffix / f"{_safe_name(entry_name)}.pkl.gz"
    if not payload_path.exists():
        raise RuntimeError(f"Shell artifact nao encontrado: {payload_path}")
    with gzip.open(payload_path, "rb") as fh:
        payload = pickle.load(fh)

    if "entry_meta" in payload and "feature_shells" in payload:
        entry = _restore_entry(payload["entry_meta"])
        shells = payload.get("feature_shells", {}).get(str(feature_id)) or []
    else:
        entry = payload["entry"]
        shells = _trace_feature_shells(
            payload["shell_manager"],
            feature_id,
            payload["ifp_length"],
            payload["ifp_count"],
        )
    if not shells:
        raise RuntimeError(f"Nenhum shell foi encontrado no cache para o fingerprint {feature_id} em {entry_name}.")
    return entry, shells, payload["pdb_dir"], f"cached_payload:{payload_path.name}"


def _coords_from_value(value):
    try:
        if callable(value):
            value = value()
    except Exception:
        return None
    try:
        coords = list(value)
        if len(coords) >= 3:
            return [float(coords[0]), float(coords[1]), float(coords[2])]
    except Exception:
        pass
    for names in (("x", "y", "z"), ("X", "Y", "Z")):
        try:
            return [float(getattr(value, name)) for name in names]
        except Exception:
            pass
    return None


def _atom_coords(atom):
    for attr in ("coord", "coords", "coordinate", "coordinates"):
        coords = _coords_from_value(getattr(atom, attr, None))
        if coords is not None:
            return coords
    try:
        return _coords_from_value(atom.get_coord())
    except Exception:
        return None


def _shell_center(shell):
    group = getattr(shell, "central_atm_grp", None)
    for attr in ("centroid", "center", "coord", "coords"):
        coords = _coords_from_value(getattr(group, attr, None))
        if coords is not None:
            return coords
    atom_coords = []
    for atom in list(getattr(group, "atoms", []) or []):
        coords = _atom_coords(atom)
        if coords is not None:
            atom_coords.append(coords)
    if atom_coords:
        total = len(atom_coords)
        return [
            sum(coords[index] for coords in atom_coords) / total
            for index in range(3)
        ]
    return None


def _add_shell_number_labels(shells, feature_id, output_path):
    try:
        from pymol import cmd
    except Exception as exc:
        _stage(f"rotulos de shells ignorados: pymol.cmd indisponivel ({type(exc).__name__}: {exc})")
        return 0

    try:
        existing_objects = list(cmd.get_object_list("all") or [])
    except Exception:
        existing_objects = []
    if not existing_objects and Path(output_path).exists():
        try:
            cmd.load(str(output_path))
        except Exception as exc:
            _stage(f"rotulos de shells ignorados: nao foi possivel recarregar PSE ({type(exc).__name__}: {exc})")
            return 0

    group_name = f"hip2l_fp_{int(feature_id)}_shell_numbers"
    label_objects = []
    for shell_index, shell in enumerate(list(shells or []), start=1):
        center = _shell_center(shell)
        if center is None:
            continue
        level = _shell_level_key(shell)
        name = f"{group_name}_S{shell_index:03d}_L{_safe_name(level)}"
        label = f"Shell {shell_index} | L{level}"
        try:
            cmd.pseudoatom(name, pos=center, label=label)
            cmd.show("spheres", name)
            cmd.show("labels", name)
            cmd.set("sphere_scale", 0.28, name)
            cmd.set("sphere_transparency", 0.25, name)
            cmd.set("label_size", 16, name)
            cmd.set("label_color", "black", name)
            cmd.color("yellow", name)
            label_objects.append(name)
        except Exception as exc:
            _stage(f"rotulo do shell {shell_index} ignorado ({type(exc).__name__}: {exc})")
    if label_objects:
        try:
            cmd.group(group_name, " ".join(label_objects))
            cmd.save(str(output_path))
        except Exception as exc:
            _stage(f"rotulos de shells criados, mas nao foi possivel salvar PSE atualizado ({type(exc).__name__}: {exc})")
            return 0
    return len(label_objects)


def _load_runtime_args():
    raw = os.environ.get("HIP2L_FP_SESSION_ARGS")
    if raw:
        return json.loads(raw)
    return {
        "workdir": sys.argv[1],
        "ifp_type": sys.argv[2],
        "entry_name": sys.argv[3],
        "feature_id": int(sys.argv[4]),
        "output_path": sys.argv[5],
    }


runtime_args = _load_runtime_args()
workdir = Path(runtime_args["workdir"])
ifp_type = str(runtime_args["ifp_type"])
entry_name = str(runtime_args["entry_name"])
feature_id = int(runtime_args["feature_id"])
output_path = Path(runtime_args["output_path"])

suffix = {"EIFP": "E", "HIFP": "H", "FIFP": "F"}.get(ifp_type)
if suffix is None:
    print(json.dumps({"error": f"Tipo IFP inv\u00e1lido: {ifp_type}"}))
    sys.exit(0)

source = ""
live_error = ""
try:
    entry, shells, pdb_source, source = _regenerate_shells_from_project(
        workdir,
        ifp_type,
        entry_name,
        feature_id,
    )
except Exception as exc:
    live_error = f"{type(exc).__name__}: {exc}"
    _stage(f"regeneracao live falhou; tentando cache legado: {live_error}")
    try:
        entry, shells, pdb_source, source = _load_cached_shell_payload(
            workdir,
            ifp_type,
            entry_name,
            feature_id,
        )
    except Exception as cache_exc:
        print(json.dumps({
            "error": (
                "Nao foi possivel regenerar shells pelo projeto LUNA nem recuperar shells do cache. "
                f"Regeneracao live: {live_error}. Cache: {type(cache_exc).__name__}: {cache_exc}"
            )
        }))
        sys.exit(0)

if not shells:
    print(json.dumps({"error": f"Nenhum shell foi encontrado para o fingerprint {feature_id} em {entry_name}."}))
    sys.exit(0)

output_path.parent.mkdir(parents=True, exist_ok=True)
_stage(f"shells recuperados: {len(shells)} ({source}); preparando ShellViewer do LUNA")
os.environ.setdefault("PYMOL_HEADLESS", "1")
os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")
os.environ.setdefault("LIBGL_ALWAYS_SOFTWARE", "1")
os.environ.setdefault("MESA_LOADER_DRIVER_OVERRIDE", "llvmpipe")
os.environ.setdefault("MPLBACKEND", "Agg")
try:
    from luna.interaction.fp.view import ShellViewer
except Exception as exc:
    print(json.dumps({"error": f"Nao foi possivel carregar ShellViewer/PyMOL do LUNA ({type(exc).__name__}: {exc})."}))
    sys.exit(0)

_stage("ShellViewer carregado; salvando sessao PSE")
try:
    viewer = ShellViewer()
    viewer.new_session([(entry, shells, pdb_source)], str(output_path))
except Exception as exc:
    print(json.dumps({"error": f"LUNA ShellViewer falhou ao salvar a sessao PSE ({type(exc).__name__}: {exc})."}))
    sys.exit(0)
if not output_path.exists():
    print(json.dumps({"error": f"LUNA ShellViewer terminou sem criar a sessao PSE: {output_path}"}))
    sys.exit(0)
shell_label_count = _add_shell_number_labels(shells, feature_id, output_path)
print(json.dumps({
    "ok": True,
    "output": str(output_path),
    "shells": len(shells),
    "shell_levels": _sorted_level_keys(_shell_level_key(shell) for shell in shells),
    "shell_labels": shell_label_count,
    "source": source,
}))
"""

_FP_DETAIL_SCRIPT = r"""
import gzip, json, pickle, sys, warnings
from collections import Counter, defaultdict
from pathlib import Path

warnings.filterwarnings("ignore", message=r'.*"import openbabel".*')

WATER_RESIDUES = {"HOH", "WAT", "WTM", "TIP", "SOL", "T3P", "H2O", "OH2", "DOD"}


def _group_has_water_residue(atm_grp):
    for atom in getattr(atm_grp, "atoms", []) or []:
        residue = getattr(atom, "parent", None)
        if residue is None:
            continue
        resname = getattr(residue, "resname", None)
        if resname is None:
            try:
                resname = residue.get_resname()
            except Exception:
                resname = ""
        if str(resname or "").strip().upper() in WATER_RESIDUES:
            return True
    return False


def _group_role(atm_grp):
    if atm_grp is None:
        return "unknown"
    try:
        if atm_grp.has_water():
            return "water"
    except Exception:
        pass
    try:
        if _group_has_water_residue(atm_grp):
            return "water"
    except Exception:
        pass
    try:
        if atm_grp.has_residue() or atm_grp.has_nucleotide():
            return "protein"
    except Exception:
        pass
    try:
        if atm_grp.has_hetatm():
            return "ligand"
    except Exception:
        pass
    return "other"


def _residue_label_from_group(atm_grp):
    atoms = list(getattr(atm_grp, "atoms", []) or [])
    labels = Counter()
    for atom in atoms:
        residue = getattr(atom, "parent", None)
        if residue is None:
            continue
        chain = "?"
        full_id = getattr(residue, "full_id", None)
        if isinstance(full_id, (list, tuple)) and len(full_id) >= 3:
            chain = str(full_id[2] or "?").strip() or "?"
        resname = str(getattr(residue, "resname", None) or getattr(residue, "get_resname", lambda: "")()).strip() or "UNK"
        resid = getattr(residue, "id", None)
        seq = ""
        if isinstance(resid, (list, tuple)) and len(resid) >= 3:
            seq = f"{resid[1]}{str(resid[2] or '').strip()}".strip()
        elif resid is not None:
            seq = str(resid).strip()
        if not seq:
            continue
        labels[f"{chain}/{resname}/{seq}"] += 1
    if not labels:
        return ""
    return labels.most_common(1)[0][0]


def _interaction_name(interaction):
    value = getattr(interaction, "type", None)
    if value is None:
        return type(interaction).__name__
    return str(value).strip() or type(interaction).__name__


def _interaction_residue_group(src_grp, trgt_grp, src_role, trgt_role):
    pair = {src_role, trgt_role}
    if pair == {"ligand", "protein"}:
        return src_grp if src_role == "protein" else trgt_grp
    if pair == {"protein", "water"}:
        return src_grp if src_role == "protein" else trgt_grp
    if pair == {"ligand", "water"}:
        return src_grp if src_role == "water" else trgt_grp
    return None


def _shell_level_key(shell):
    value = getattr(shell, "level", None)
    try:
        return str(int(value))
    except Exception:
        return str(value if value is not None else "unknown")


workdir = Path(sys.argv[1])
ifp_type = sys.argv[2]
output_path = Path(sys.argv[3])
suffix = {"EIFP": "E", "HIFP": "H", "FIFP": "F"}.get(ifp_type)
if suffix is None:
    print(json.dumps({"error": f"Tipo IFP invalido: {ifp_type}"}))
    sys.exit(0)

shell_dir = workdir / "results" / "fingerprints" / "_shells" / suffix
if not shell_dir.exists():
    print(json.dumps({"error": f"Diretorio de shells nao encontrado: {shell_dir}"}))
    sys.exit(0)

feature_details = {}
files = sorted(shell_dir.glob("*.pkl.gz"))
for payload_path in files:
    with gzip.open(payload_path, "rb") as fh:
        payload = pickle.load(fh)
    entry_meta = payload.get("entry_meta") or {}
    entry_name = str(entry_meta.get("entry_str") or payload_path.stem)
    feature_shells = payload.get("feature_shells") or {}
    for feature_key, shells in feature_shells.items():
        feature_id = str(feature_key)
        detail = feature_details.setdefault(
            feature_id,
            {
                "interaction_counts": {},
                "residue_counts": {},
                "pair_counts": {},
                "shell_level_counts": {},
                "entries": {},
            },
        )
        entry_info = detail["entries"].setdefault(
            entry_name,
            {
                "shell_count": 0,
                "interaction_counts": {},
                "residue_counts": {},
                "pair_counts": {},
                "shell_level_counts": {},
            },
        )
        entry_info["shell_count"] += len(shells)
        for shell in list(shells or []):
            level_key = _shell_level_key(shell)
            detail["shell_level_counts"][level_key] = detail["shell_level_counts"].get(level_key, 0) + 1
            entry_info["shell_level_counts"][level_key] = entry_info["shell_level_counts"].get(level_key, 0) + 1
            interactions = list(getattr(shell, "interactions", []) or [])
            for interaction in interactions:
                src_grp = getattr(interaction, "src_grp", None)
                trgt_grp = getattr(interaction, "trgt_grp", None)
                src_role = _group_role(src_grp)
                trgt_role = _group_role(trgt_grp)
                residue_group = _interaction_residue_group(src_grp, trgt_grp, src_role, trgt_role)
                if residue_group is None:
                    continue
                interaction_name = _interaction_name(interaction)
                residue_label = _residue_label_from_group(residue_group)
                pair_key = interaction_name if not residue_label else f"{interaction_name}||{residue_label}"

                detail["interaction_counts"][interaction_name] = detail["interaction_counts"].get(interaction_name, 0) + 1
                entry_info["interaction_counts"][interaction_name] = entry_info["interaction_counts"].get(interaction_name, 0) + 1

                if residue_label:
                    detail["residue_counts"][residue_label] = detail["residue_counts"].get(residue_label, 0) + 1
                    entry_info["residue_counts"][residue_label] = entry_info["residue_counts"].get(residue_label, 0) + 1

                detail["pair_counts"][pair_key] = detail["pair_counts"].get(pair_key, 0) + 1
                entry_info["pair_counts"][pair_key] = entry_info["pair_counts"].get(pair_key, 0) + 1

payload = {
    "ifp_type": ifp_type,
    "feature_details": feature_details,
}
output_path.parent.mkdir(parents=True, exist_ok=True)
output_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
print(json.dumps({"ok": True, "output": str(output_path), "features": len(feature_details), "entries": len(files)}))
"""

_FP_DASHBOARD_SCRIPT = r"""
import json, sys
from pathlib import Path

package_root = Path(sys.argv[1])
workdir = Path(sys.argv[2])
ifp_type = str(sys.argv[3]).upper()
labels_csv = sys.argv[4]
labels_id_column = sys.argv[5]
labels_column = sys.argv[6]
algorithm_preference = sys.argv[7]
task_kind_preference = sys.argv[8]
use_otsu_threshold = str(sys.argv[9]).strip().lower() in {"1", "true", "yes", "sim"}
random_seed = sys.argv[10] if len(sys.argv) > 10 else ""

sys.path.insert(0, str(package_root))

from luna_gui.core.results_analysis import build_fp_analysis_dashboard, load_fp_analysis_artifacts

artifacts = load_fp_analysis_artifacts(workdir)
artifact = artifacts.get(ifp_type)
if artifact is None:
    print(json.dumps({"error": f"Artefato de fingerprint nao encontrado para {ifp_type}."}))
    sys.exit(0)

dashboard = build_fp_analysis_dashboard(
    workdir,
    artifact,
    labels_csv=labels_csv or None,
    labels_id_column=labels_id_column or None,
    labels_column=labels_column or None,
    algorithm_preference=algorithm_preference or "gradient_boosting",
    task_kind_preference=task_kind_preference or None,
    use_otsu_threshold=use_otsu_threshold,
    random_seed=random_seed or None,
)
print(json.dumps(dashboard, ensure_ascii=False))
"""

_PSE_FILTER_SCRIPT = r"""
import ast, configparser, fnmatch, gzip, json, pickle, re, shutil, sys
from pathlib import Path


def _safe_name(value):
    return re.sub(r"[^A-Za-z0-9_.-]+", "_", str(value)).strip("_") or "filtered"


def _load_project(workdir):
    candidates = sorted(Path(workdir).glob("project_v*.pkl.gz"), reverse=True)
    if not candidates:
        return None, f"Nenhum project_v*.pkl.gz encontrado em {workdir}."
    errors = []
    for candidate in candidates:
        try:
            with gzip.open(candidate, "rb") as fh:
                return pickle.load(fh), ""
        except Exception as exc:
            errors.append(f"{candidate.name}: {type(exc).__name__}: {exc}")
    return None, "Falha ao reabrir o projeto salvo pelo LUNA (" + "; ".join(errors[:3]) + ")."


def _load_residue_matrix(workdir):
    path = Path(workdir) / "results" / "residue_matrix.json"
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None


def _parse_rules(cfg_path):
    parser = configparser.ConfigParser()
    parser.optionxform = str
    parser.read(cfg_path, encoding="utf-8")
    rules = {}
    for section in parser.sections():
        accept_all = parser.get(section, "accept_all", fallback="False").strip().lower() == "true"
        raw_accept_only = parser.get(section, "accept_only", fallback="").strip()
        selectors = []
        if raw_accept_only:
            try:
                parsed = ast.literal_eval(raw_accept_only)
                if isinstance(parsed, (list, tuple)):
                    selectors = [str(item).strip() for item in parsed if str(item).strip()]
                else:
                    selectors = [str(parsed).strip()]
            except Exception:
                selectors = [part.strip().strip("'\"") for part in raw_accept_only.split(",") if part.strip()]
        rules[section.lower()] = {
            "name": section,
            "accept_all": accept_all,
            "selectors": selectors,
        }
    return rules


def _interaction_name(interaction):
    value = getattr(interaction, "type", None)
    if value is None:
        return type(interaction).__name__
    return str(value).strip() or type(interaction).__name__


def _atoms_from_group(group):
    return list(getattr(group, "atoms", []) or [])


def _atom_parts(atom):
    residue = getattr(atom, "parent", None)
    chain = "*"
    resname = "*"
    seq = "*"
    if residue is not None:
        full_id = getattr(residue, "full_id", None)
        if isinstance(full_id, (list, tuple)) and len(full_id) >= 3:
            chain = str(full_id[2] or "*").strip() or "*"
        resname = str(getattr(residue, "resname", None) or getattr(residue, "get_resname", lambda: "")()).strip() or "*"
        resid = getattr(residue, "id", None)
        if isinstance(resid, (list, tuple)) and len(resid) >= 2:
            seq = f"{resid[1]}{str(resid[2] or '').strip()}".strip() or "*"
        elif resid is not None:
            seq = str(resid).strip() or "*"
    atom_name = str(getattr(atom, "name", None) or getattr(atom, "get_name", lambda: "")()).strip() or "*"
    return [chain.upper(), resname.upper(), seq.upper(), atom_name.upper()]


def _selector_matches_atom(selector, atom):
    parts = [part.strip() or "*" for part in str(selector).split("/")]
    parts = (parts + ["*"] * 4)[:4]
    for pattern, value in zip(parts, _atom_parts(atom)):
        if pattern == "*":
            continue
        if not fnmatch.fnmatchcase(value.upper(), pattern.upper()):
            return False
    return True


def _selector_matches_residue_label(selector, residue_label):
    parts = [part.strip() or "*" for part in str(selector).split("/")]
    parts = (parts + ["*"] * 4)[:4]
    residue_parts = [part.strip() or "*" for part in str(residue_label).split("/")]
    residue_parts = (residue_parts + ["*"] * 3)[:3]
    for pattern, value in zip(parts[:3], residue_parts):
        if pattern == "*":
            continue
        if not fnmatch.fnmatchcase(value.upper(), pattern.upper()):
            return False
    return True


def _interaction_matches_rule(interaction, rule):
    if rule.get("accept_all"):
        return True
    selectors = list(rule.get("selectors") or [])
    if not selectors:
        return False
    atoms = []
    atoms.extend(_atoms_from_group(getattr(interaction, "src_grp", None)))
    atoms.extend(_atoms_from_group(getattr(interaction, "trgt_grp", None)))
    return any(_selector_matches_atom(selector, atom) for selector in selectors for atom in atoms)


def _iter_interactions(manager):
    try:
        return list(manager)
    except Exception:
        pass
    for attr in ("interactions", "interactions_list", "_interactions"):
        value = getattr(manager, attr, None)
        if value is not None:
            try:
                return list(value)
            except Exception:
                pass
    return []


def _find_existing_pse_files(workdir):
    files = []
    for folder in (Path(workdir) / "results" / "pse", Path(workdir) / "pse"):
        if folder.exists() and folder.is_dir():
            files.extend(folder.glob("*.pse"))
    return sorted(files)


def _pse_for_entry(pse_files, entry_name):
    safe_variants = {
        _safe_name(entry_name).lower(),
        str(entry_name).replace(":", "_").replace("/", "_").lower(),
        Path(str(entry_name)).stem.lower(),
    }
    for path in pse_files:
        if path.stem.lower() in safe_variants:
            return path
    normalized_entry = _safe_name(entry_name).lower()
    for path in pse_files:
        stem = path.stem.lower()
        if normalized_entry in stem or stem in normalized_entry:
            return path
    return None


def _entry_matches_cached_rules(matrix_artifact, entry_index, rules):
    entries = list(matrix_artifact.get("entries") or [])
    residues = list(matrix_artifact.get("residues") or [])
    matrices = matrix_artifact.get("matrix") or {}
    wildcard = rules.get("*")
    matched = 0

    for interaction_name, rows in matrices.items():
        rule = rules.get(str(interaction_name).lower()) or wildcard
        if not rule:
            continue
        try:
            row = list(rows[entry_index])
        except Exception:
            continue
        positive_residues = [
            residue
            for residue, value in zip(residues, row)
            if float(value or 0.0) > 0.0
        ]
        if not positive_residues:
            continue
        if rule.get("accept_all"):
            matched += len(positive_residues)
            continue
        selectors = list(rule.get("selectors") or [])
        if selectors and any(
            _selector_matches_residue_label(selector, residue)
            for selector in selectors
            for residue in positive_residues
        ):
            matched += 1
    return matched


def _copy_cached_pse_sessions(workdir, rules, output_dir, original_error):
    matrix_artifact = _load_residue_matrix(workdir)
    if not matrix_artifact:
        return {
            "error": original_error
            + " Também não foi encontrado results/residue_matrix.json para aplicar filtragem por arquivo.",
        }
    pse_files = _find_existing_pse_files(workdir)
    if not pse_files:
        return {
            "error": original_error
            + " Também não foram encontradas sessões .pse existentes para copiar.",
        }

    output_dir.mkdir(parents=True, exist_ok=True)
    created = 0
    matched_interactions = 0
    warnings = [
        original_error,
        "Fallback usado: o projeto salvo não reabriu, então a GUI filtrou arquivos .pse existentes usando residue_matrix.json. "
        "As sessões copiadas preservam o conteúdo visual original; a filtragem seleciona quais arquivos entram na subpasta.",
    ]
    for entry_index, entry_name in enumerate(list(matrix_artifact.get("entries") or [])):
        matched = _entry_matches_cached_rules(matrix_artifact, entry_index, rules)
        if matched <= 0:
            continue
        source = _pse_for_entry(pse_files, entry_name)
        if source is None:
            warnings.append(f"PSE não encontrado para {entry_name}.")
            continue
        target = output_dir / source.name
        shutil.copy2(source, target)
        created += 1
        matched_interactions += matched

    return {
        "ok": True,
        "fallback": True,
        "output_dir": str(output_dir),
        "created": created,
        "matched_interactions": matched_interactions,
        "warnings": warnings[:20],
    }


workdir = Path(sys.argv[1])
cfg_path = Path(sys.argv[2])
output_dir = Path(sys.argv[3])

if not cfg_path.exists():
    print(json.dumps({"error": f"Arquivo de regras nao encontrado: {cfg_path}"}))
    sys.exit(0)

rules = _parse_rules(cfg_path)
if not rules:
    print(json.dumps({"error": "O arquivo .cfg nao contem regras."}))
    sys.exit(0)

print(json.dumps(_copy_cached_pse_sessions(
    workdir,
    rules,
    output_dir,
    "Filtragem segura: a GUI nao abriu PyMOL/OpenGL dentro do helper; foram usados "
    "residue_matrix.json e sessoes .pse ja existentes para evitar SIGSEGV.",
), ensure_ascii=False))
sys.exit(0)

project, error = _load_project(workdir)
if error:
    print(json.dumps(_copy_cached_pse_sessions(workdir, rules, output_dir, error), ensure_ascii=False))
    sys.exit(0)

output_dir.mkdir(parents=True, exist_ok=True)
created = 0
matched_interactions = 0
warnings = []
wildcard = rules.get("*")
viewer = InteractionViewer(show_hydrop_surface=False)

for entry in list(getattr(project, "entries", []) or []):
    try:
        er = project.get_entry_results(entry)
        selected = []
        for interaction in _iter_interactions(er.interactions_mngr):
            name = _interaction_name(interaction)
            rule = rules.get(name.lower()) or wildcard
            if rule and _interaction_matches_rule(interaction, rule):
                selected.append(interaction)
        if not selected:
            continue
        matched_interactions += len(selected)
        safe_entry = _safe_name(entry.to_string() if hasattr(entry, "to_string") else str(entry))
        pse_path = output_dir / f"{safe_entry}.pse"
        pdb_file = getattr(entry, "pdb_file", "")
        if not pdb_file:
            pdb_id = getattr(entry, "pdb_id", "")
            pdb_file = workdir / "pdbs" / f"{pdb_id}.pdb"
        viewer.new_session([(entry, selected, str(pdb_file))], str(pse_path))
        created += 1
    except Exception as exc:
        warnings.append(f"{entry}: {type(exc).__name__}: {exc}")

print(json.dumps({
    "ok": True,
    "output_dir": str(output_dir),
    "created": created,
    "matched_interactions": matched_interactions,
    "warnings": warnings[:20],
}, ensure_ascii=False))
"""


def run_analysis(py_exe: str, workdir: str, timeout: int = 300) -> dict:
    wd = Path(workdir)
    cached = _load_cached_json(wd / "results" / "analysis_summary.json")
    if cached is not None:
        return cached
    return analysis_helper.run_analysis(py_exe, workdir, timeout=timeout)


def _residue_matrix_has_ligand_atoms(artifact: dict | None) -> bool:
    if not isinstance(artifact, dict):
        return False
    return bool(artifact.get("ligand_atoms")) and isinstance(artifact.get("ligand_atom_matrix"), dict)


def run_residue_matrix(
    py_exe: str,
    workdir: str,
    timeout: int = 600,
    require_ligand_atoms: bool = False,
) -> dict:
    wd = Path(workdir)
    cached = _load_cached_json(wd / "results" / "residue_matrix.json")
    if cached is not None and (not require_ligand_atoms or _residue_matrix_has_ligand_atoms(cached)):
        return cached
    result = analysis_helper.run_residue_matrix(py_exe, workdir, timeout=timeout)
    if "error" in result and cached is not None:
        return cached
    return result


def _fp_session_env(py_exe: str) -> dict[str, str]:
    env = python_process_env(py_exe)
    env.setdefault("PYMOL_HEADLESS", "1")
    env.setdefault("QT_QPA_PLATFORM", "offscreen")
    env.setdefault("LIBGL_ALWAYS_SOFTWARE", "1")
    env.setdefault("MESA_LOADER_DRIVER_OVERRIDE", "llvmpipe")
    env.setdefault("MPLBACKEND", "Agg")
    return env


def _path_is_inside(child: Path, parent: Path) -> bool:
    try:
        child_resolved = child.resolve()
        parent_resolved = parent.resolve()
    except OSError:
        return False
    return child_resolved == parent_resolved or parent_resolved in child_resolved.parents


def _find_env_pymol_executable(py_exe: str) -> Path | None:
    try:
        prefix = python_prefix(py_exe)
    except Exception:
        return None
    for candidate in iter_pymol_candidates(py_exe):
        try:
            if candidate.exists() and candidate.is_file() and _path_is_inside(candidate, prefix):
                return candidate
        except OSError:
            continue
    return None


def generate_fp_session(
    py_exe: str,
    workdir: str,
    ifp_type: str,
    entry_name: str,
    feature_id: int,
    output_path: str,
    timeout: int = 600,
) -> dict:
    """Generate a PyMOL PSE session for one fingerprint feature using LUNA shells."""
    if not py_exe or not Path(py_exe).exists():
        return {"error": "Python do luna-env n\u00e3o encontrado."}
    if not Path(workdir).exists():
        return {"error": f"Workdir n\u00e3o existe: {workdir}"}

    payload = json.dumps(
        {
            "workdir": str(workdir),
            "ifp_type": str(ifp_type),
            "entry_name": str(entry_name),
            "feature_id": int(feature_id),
            "output_path": str(output_path),
        },
        ensure_ascii=False,
    )
    env = _fp_session_env(py_exe)
    env["HIP2L_FP_SESSION_ARGS"] = payload
    pymol_exe = _find_env_pymol_executable(py_exe)

    try:
        if pymol_exe is not None:
            with tempfile.TemporaryDirectory(prefix="hip2l_fp_session_") as tmp_dir:
                script_path = Path(tmp_dir) / "generate_fp_session.py"
                script_path.write_text(_FP_SESSION_SCRIPT, encoding="utf-8")
                result = subprocess.run(
                    [str(pymol_exe), "-cq", "-r", str(script_path)],
                    capture_output=True,
                    text=True,
                    timeout=timeout,
                    env=env,
                )
        else:
            result = subprocess.run(
                [
                    py_exe,
                    "-c",
                    _FP_SESSION_SCRIPT,
                    workdir,
                    ifp_type,
                    entry_name,
                    str(int(feature_id)),
                    output_path,
                ],
                capture_output=True,
                text=True,
                timeout=timeout,
                env=env,
            )
    except subprocess.TimeoutExpired:
        return {"error": "A geração da sessão de fingerprint excedeu o tempo limite."}
    except Exception as exc:
        return {"error": str(exc)}

    if result.returncode != 0:
        prefix = "Helper PyMOL/LUNA falhou" if pymol_exe is not None else "Helper LUNA/PyMOL falhou"
        return _helper_failure(result, prefix=prefix)
    try:
        return _helper_json_from_stdout(result.stdout)
    except Exception:
        return _helper_invalid_output(result)


def run_fp_detail_analysis(
    py_exe: str,
    workdir: str,
    ifp_type: str,
    timeout: int = 900,
) -> dict:
    """Generate or load cached interaction/residue summaries for one IFP type."""
    wd = Path(workdir)
    if not wd.exists():
        return {"error": f"Workdir n\u00e3o existe: {workdir}"}

    suffix = {value: key for key, value in IFP_SUFFIX_TO_TYPE.items()}.get(str(ifp_type).upper())
    if suffix is None:
        return {"error": f"Tipo IFP inv\u00e1lido: {ifp_type}"}

    output_path = wd / "results" / "fingerprints" / f"fp_detail_{suffix}.json"
    cached = _load_cached_json(output_path)
    if cached is not None and _fp_detail_cache_has_shell_levels(cached):
        return cached

    shell_level_only = _build_shell_level_only_fp_detail(wd, str(ifp_type).upper(), output_path)
    if shell_level_only is not None:
        return shell_level_only

    return {
        "error": (
            "fp_detail nao disponivel. Reexecute o calculo de fingerprints com a versao atual "
            "para gerar detalhes de interacao/residuo diretamente durante o LUNA, sem reabrir "
            "pickles antigos de shells que podem derrubar o helper."
        )
    }

def run_fp_dashboard_analysis(
    py_exe: str,
    workdir: str,
    ifp_type: str,
    labels_csv: str = "",
    labels_id_column: str = "",
    labels_column: str = "",
    algorithm_preference: str = "gradient_boosting",
    task_kind_preference: str = "",
    use_otsu_threshold: bool = False,
    random_seed: int | str | None = None,
    timeout: int = 900,
) -> dict:
    if not py_exe or not Path(py_exe).exists():
        return {"error": "Python do luna-env não encontrado."}
    wd = Path(workdir)
    if not wd.exists():
        return {"error": f"Workdir não existe: {workdir}"}

    package_root = Path(__file__).resolve().parents[2]
    try:
        result = subprocess.run(
            [
                py_exe,
                "-c",
                _FP_DASHBOARD_SCRIPT,
                str(package_root),
                str(wd),
                str(ifp_type).upper(),
                str(labels_csv or ""),
                str(labels_id_column or ""),
                str(labels_column or ""),
                str(algorithm_preference or "gradient_boosting"),
                str(task_kind_preference or ""),
                "1" if use_otsu_threshold else "0",
                "" if random_seed is None else str(random_seed),
            ],
            capture_output=True,
            text=True,
            timeout=timeout,
            env=python_process_env(py_exe),
        )
    except subprocess.TimeoutExpired:
        return {"error": "A geração do dashboard de fingerprints excedeu o tempo limite."}
    except Exception as exc:
        return {"error": str(exc)}

    if result.returncode != 0:
        return _helper_failure(result)
    try:
        return _helper_json_from_stdout(result.stdout)
    except Exception:
        return _helper_invalid_output(result)


def generate_filtered_pse_sessions(
    py_exe: str,
    workdir: str,
    binding_modes_cfg: str,
    output_dir: str,
    timeout: int = 1800,
) -> dict:
    """Generate filtered PyMOL sessions from a saved LUNA project."""
    if not py_exe or not Path(py_exe).exists():
        return {"error": "Python do luna-env não encontrado."}
    if not Path(workdir).exists():
        return {"error": f"Workdir não existe: {workdir}"}
    if not Path(binding_modes_cfg).exists():
        return {"error": f"Arquivo .cfg não existe: {binding_modes_cfg}"}

    try:
        result = subprocess.run(
            [
                py_exe,
                "-c",
                _PSE_FILTER_SCRIPT,
                str(workdir),
                str(binding_modes_cfg),
                str(output_dir),
            ],
            capture_output=True,
            text=True,
            timeout=timeout,
            env=python_process_env(py_exe),
        )
    except subprocess.TimeoutExpired:
        return {"error": "A filtragem de sessões PyMOL excedeu o tempo limite."}
    except Exception as exc:
        return {"error": str(exc)}

    if result.returncode != 0:
        return _helper_failure(result)
    try:
        return _helper_json_from_stdout(result.stdout)
    except Exception:
        return _helper_invalid_output(result)


def _load_cached_json(path: Path) -> dict | None:
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None
