"""Portable semantic index for plots generated by HIP2LInterActomics."""
from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field
from pathlib import Path


MANIFEST_SCHEMA_VERSION = 1
MANIFEST_FILENAME = "plot_manifest.json"
LANGUAGES = ("en", "pt", "es")
PROFILES = ("screen", "report")


@dataclass(frozen=True)
class PlotRecord:
    plot_id: str
    language: str
    profile: str
    path: str
    title: str
    caption: str
    sequence: int
    ifp_type: str = ""
    model: str = ""
    category: str = ""

    def __post_init__(self) -> None:
        if self.language not in LANGUAGES:
            raise ValueError(f"Unsupported plot language: {self.language}")
        if self.profile not in PROFILES:
            raise ValueError(f"Unsupported plot profile: {self.profile}")
        if not str(self.plot_id).strip():
            raise ValueError("plot_id cannot be empty")


@dataclass
class PlotManifest:
    records: list[PlotRecord] = field(default_factory=list)
    schema_version: int = MANIFEST_SCHEMA_VERSION

    def add(self, record: PlotRecord) -> None:
        identity = (
            record.plot_id,
            record.language,
            record.profile,
            record.ifp_type,
            record.model,
        )
        self.records = [
            item
            for item in self.records
            if (
                item.plot_id,
                item.language,
                item.profile,
                item.ifp_type,
                item.model,
            ) != identity
        ]
        self.records.append(record)

    def select(
        self,
        *,
        language: str,
        profile: str,
        ifp_type: str | None = None,
        model: str | None = None,
    ) -> list[PlotRecord]:
        selected = [
            record
            for record in self.records
            if record.language == language
            and record.profile == profile
            and (ifp_type is None or record.ifp_type == ifp_type)
            and (model is None or record.model == model)
        ]
        return sorted(
            selected,
            key=lambda record: (
                int(record.sequence),
                record.ifp_type,
                record.model,
                record.plot_id,
            ),
        )

    def save(self, path: str | Path) -> Path:
        output = Path(path)
        output.parent.mkdir(parents=True, exist_ok=True)
        temporary = output.with_name(f".{output.name}.part")
        payload = {
            "schema_version": self.schema_version,
            "records": [asdict(record) for record in self.records],
        }
        temporary.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
        temporary.replace(output)
        return output

    @classmethod
    def load(cls, path: str | Path) -> "PlotManifest":
        source = Path(path)
        if not source.exists():
            return cls()
        payload = json.loads(source.read_text(encoding="utf-8"))
        if int(payload.get("schema_version", 0) or 0) != MANIFEST_SCHEMA_VERSION:
            return cls()
        records = [PlotRecord(**row) for row in payload.get("records", [])]
        return cls(records=records)


def manifest_path(workdir: str | Path) -> Path:
    return Path(workdir) / "results" / "plots" / MANIFEST_FILENAME


def load_manifest(workdir: str | Path) -> PlotManifest:
    return PlotManifest.load(manifest_path(workdir))


def plot_output_path(
    workdir: str | Path,
    language: str,
    profile: str,
    category: str,
    filename: str,
) -> Path:
    if language not in LANGUAGES:
        raise ValueError(f"Unsupported plot language: {language}")
    if profile not in PROFILES:
        raise ValueError(f"Unsupported plot profile: {profile}")
    return Path(workdir) / "results" / "plots" / language / profile / category / filename


def portable_plot_path(path: str | Path, workdir: str | Path) -> str:
    source = Path(path)
    try:
        return source.resolve().relative_to(Path(workdir).resolve()).as_posix()
    except (OSError, ValueError):
        return str(source)


def resolve_plot_path(record: PlotRecord, workdir: str | Path) -> Path:
    path = Path(record.path)
    return path if path.is_absolute() else Path(workdir) / path
